### ISSUE TITLE
Fix: Error when exporting registrations

### ISSUE THREAD

**Issue by cdobbyn** [BCGamer/website#307]
ERROR 2016-03-08 11:47:05,661 base Internal Server Error: /frontdesk/export/lantasy-2016/registrations/
Traceback (most recent call last):
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/braces/views/_access.py", line 337, in dispatch
    request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/list.py", line 175, in get
    return self.render_to_response(context)
  File "./website/apps/badgebro/views.py", line 370, in render_to_response
    registration.date_added.time(),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
ERROR 2016-03-08 11:47:05,661 base Internal Server Error: /frontdesk/export/lantasy-2016/registrations/
Traceback (most recent call last):
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/braces/views/_access.py", line 337, in dispatch
    request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bcgamer/www.lantasy.com/env/local/lib/python2.7/site-packages/django/views/generic/list.py", line 175, in get
    return self.render_to_response(context)
  File "./website/apps/badgebro/views.py", line 370, in render_to_response
    registration.date_added.time(),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)

**Comment by cdobbyn** [comment]
Fixed in 549238a.
